### ISSUE TITLE
[docker] CRITICAL:pip.subprocessor:Error [Errno 2] No such file or directory: 'git'

### ISSUE THREAD

**Issue by a-w11** [jantman/awslimitchecker#471] opened 2020-07-10 08:49 UTC
Hello,

I have issue with docker-compose stack, after few errors in logs container is going to restarting state.

docker-compose:
```
version: "3.3"
services:
  monitor:
    image: jantman/awslimitchecker
    restart: unless-stopped
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    logging:
      driver: json-file
      options:
        max-size: "100M"
        max-file: "5"
```

Log:
```
monitor_1  | CRITICAL:pip.subprocessor:Error [Errno 2] No such file or directory: 'git' while executing command git config --get-regexp 'remote\..*\.url'
monitor_1  | awslimitchecker 8.0.2 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
monitor_1  | WARNING:awslimitchecker.trustedadvisor:Cannot check TrustedAdvisor: AWS Premium Support Subscription is required to use this service.
```

**Comment by jantman** [comment] 2020-07-10 12:02
@a-w11 This sounds to me like it's a duplicate of #465... but that doesn't actually affect the functionality, it just logs a really angry (supposedly critical-level) message. Can you please confirm if awslimitchecker is actually working normally or not?

Also, please note that awslimitchecker is *not* a service, it's a one-shot command. You run it and it checks your limits, prints some information if any of them are over thresholds, and then exits. It's normally run once a day, or a few times a day. The compose file above is telling it to run as a service and to restart unless stopped, so it's essentially expected that the container is going to print some logs and then restart. The logs you provided make it seem like awslimitchecker is working normally but not finding any problems.

Could you please re-run with verbose logging enabled (I believe that adding ``command: "-v"`` to your compose file will do this).

**Comment by jantman** [comment] 2020-08-31 11:23
Closing due to lack of response, and likely duplicate.

**Closed by jantman** 2020-08-31 11:23 UTC
