### ISSUE TITLE
Number of running on-demand ec2 instances not accurate

### ISSUE THREAD

**Issue by yaron-idan** [jantman/awslimitchecker#193] opened 2016-06-30 12:32 UTC
### Version

0.4.3

### Installation Method

Installed on an AWS Ubuntu instance using the exact guidelines here - https://awslimitchecker.readthedocs.io/en/latest/getting_started.html#installing

### Supporting Software Versions

Python 2.7.6, virtualenv 1.11.4.
3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

### Actual Output

```
awslimitchecker 0.4.3 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
[DEBUG base.py:202 - awslimitchecker.services.base.set_limit_override() ] Overriding ELB limit Active load balancers; default=40 override=20
[DEBUG base.py:202 - awslimitchecker.services.base.set_limit_override() ] Overriding VPC limit VPCs; default=20 override=5
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region us-east-1
[INFO connectable.py:120 - awslimitchecker.connectable.connect() ] Connected to support in region us-east-1
[INFO trustedadvisor.py:138 - awslimitchecker.trustedadvisor._poll() ] Beginning TrustedAdvisor poll
[DEBUG trustedadvisor.py:175 - awslimitchecker.trustedadvisor._get_limit_check_id() ] Querying Trusted Advisor checks
[WARNING trustedadvisor.py:184 - awslimitchecker.trustedadvisor._get_limit_check_id() ] Cannot check TrustedAdvisor: AWS Premium Support Subscription is required to use this service.
[INFO trustedadvisor.py:141 - awslimitchecker.trustedadvisor._poll() ] TrustedAdvisor.have_ta is False; not polling TA
[DEBUG trustedadvisor.py:215 - awslimitchecker.trustedadvisor._update_services() ] Updating TA limits on all services
[INFO trustedadvisor.py:231 - awslimitchecker.trustedadvisor._update_services() ] Done updating TA limits on all services
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region None
[INFO connectable.py:138 - awslimitchecker.connectable.connect_resource() ] Connected to iam (resource) in region aws-global
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccessKeysPerUserQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccountAccessKeysPresent
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccountMFAEnabled
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccountSigningCertificatesPresent
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AssumeRolePolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AttachedPoliciesPerGroupQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AttachedPoliciesPerRoleQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AttachedPoliciesPerUserQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: GroupPolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: GroupsPerUserQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: MFADevices
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: MFADevicesInUse
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: PolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: Providers
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: RolePolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: SigningCertificatesPerUserQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: UserPolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: VersionsPerPolicyQuota
[DEBUG iam.py:71 - awslimitchecker.services.iam.find_usage() ] Checking usage for service IAM
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccessKeysPerUserQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccountAccessKeysPresent
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccountMFAEnabled
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccountSigningCertificatesPresent
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AssumeRolePolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AttachedPoliciesPerGroupQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AttachedPoliciesPerRoleQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AttachedPoliciesPerUserQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: GroupPolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: GroupsPerUserQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: MFADevices
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: MFADevicesInUse
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: PolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: Providers
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: RolePolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: SigningCertificatesPerUserQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: UserPolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: VersionsPerPolicyQuota
[DEBUG iam.py:76 - awslimitchecker.services.iam.find_usage() ] Done checking usage.
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region None
[INFO connectable.py:120 - awslimitchecker.connectable.connect() ] Connected to ses in region us-east-1
[DEBUG ses.py:61 - awslimitchecker.services.ses.find_usage() ] Checking usage for service SES
[DEBUG ses.py:74 - awslimitchecker.services.ses.find_usage() ] Done checking usage.
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region None
[INFO connectable.py:120 - awslimitchecker.connectable.connect() ] Connected to rds in region us-east-1
[INFO rds.py:277 - awslimitchecker.services.rds._update_limits_from_api() ] Querying RDS DescribeAccountAttributes for limits
[DEBUG rds.py:289 - awslimitchecker.services.rds._update_limits_from_api() ] Done setting limits from API.
[DEBUG rds.py:79 - awslimitchecker.services.rds.find_usage() ] Checking usage for service RDS
[INFO rds.py:277 - awslimitchecker.services.rds._update_limits_from_api() ] Querying RDS DescribeAccountAttributes for limits
[DEBUG rds.py:289 - awslimitchecker.services.rds._update_limits_from_api() ] Done setting limits from API.
[DEBUG rds.py:89 - awslimitchecker.services.rds.find_usage() ] Done checking usage.
[DEBUG elb.py:61 - awslimitchecker.services.elb.find_usage() ] Checking usage for service ELB
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region None
[INFO connectable.py:120 - awslimitchecker.connectable.connect() ] Connected to elb in region us-east-1
[DEBUG elb.py:82 - awslimitchecker.services.elb.find_usage() ] Done checking usage.
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region None
[INFO connectable.py:120 - awslimitchecker.connectable.connect() ] Connected to autoscaling in region us-east-1
[INFO autoscaling.py:145 - awslimitchecker.services.autoscaling._update_limits_from_api() ] Querying EC2 DescribeAccountAttributes for limits
[DEBUG autoscaling.py:61 - awslimitchecker.services.autoscaling.find_usage() ] Checking usage for service AutoScaling
[DEBUG autoscaling.py:90 - awslimitchecker.services.autoscaling.find_usage() ] Done checking usage.
[DEBUG cloudformation.py:107 - awslimitchecker.services.cloudformation._update_limits_from_api() ] Setting CloudFormation limits from API
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region None
[INFO connectable.py:120 - awslimitchecker.connectable.connect() ] Connected to cloudformation in region us-east-1
[DEBUG cloudformation.py:63 - awslimitchecker.services.cloudformation.find_usage() ] Checking usage for service CloudFormation
[DEBUG cloudformation.py:78 - awslimitchecker.services.cloudformation.find_usage() ] Done checking usage.
[DEBUG s3.py:60 - awslimitchecker.services.s3.find_usage() ] Checking usage for service S3
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region None
[INFO connectable.py:138 - awslimitchecker.connectable.connect_resource() ] Connected to s3 (resource) in region us-east-1
[DEBUG s3.py:71 - awslimitchecker.services.s3.find_usage() ] Done checking usage.
[DEBUG elasticbeanstalk.py:60 - awslimitchecker.services.elasticbeanstalk.find_usage() ] Checking usage for service ElasticBeanstalk
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region None
[INFO connectable.py:120 - awslimitchecker.connectable.connect() ] Connected to elasticbeanstalk in region us-east-1
[DEBUG elasticbeanstalk.py:68 - awslimitchecker.services.elasticbeanstalk.find_usage() ] Done checking usage.
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region None
[INFO connectable.py:120 - awslimitchecker.connectable.connect() ] Connected to ec2 in region us-east-1
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region None
[INFO connectable.py:138 - awslimitchecker.connectable.connect_resource() ] Connected to ec2 (resource) in region us-east-1
[INFO ec2.py:199 - awslimitchecker.services.ec2._update_limits_from_api() ] Querying EC2 DescribeAccountAttributes for limits
[DEBUG ec2.py:216 - awslimitchecker.services.ec2._update_limits_from_api() ] Done setting limits from API
[DEBUG ec2.py:62 - awslimitchecker.services.ec2.find_usage() ] Checking usage for service EC2
[DEBUG ec2.py:154 - awslimitchecker.services.ec2._instance_usage() ] Getting usage for on-demand instances
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-2f368ad6 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-3d1a51c4 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-5a2abbdd in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-793da316 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-4be0d1fb in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-cbd03e78 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-da69b44a in state terminated
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-547b2e35 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-8dbac916 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-0493a4fd in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-23520c8b in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-1a520cb2 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-2a21229a in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-bffc1f0c in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-c6888575 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-55976ca8 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-2d7b08b6 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-f9292664 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-001341a8 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-031341ab in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-6cd8f3f0 in state terminated
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-ad9e4355 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-43a8136d in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-318d8d81 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-f96e5555 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-32c8bab6 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-188f2888 in state terminated
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-c5bbb575 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-722edc8a in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-20636190 in state stopped
[DEBUG ec2.py:123 - awslimitchecker.services.ec2._get_reserved_instance_count() ] Getting reserved instance information
[DEBUG ec2.py:129 - awslimitchecker.services.ec2._get_reserved_instance_count() ] Skipping ReservedInstance b0dfb371-f10f-4152-a354-24186962be4d with state retired
[DEBUG ec2.py:129 - awslimitchecker.services.ec2._get_reserved_instance_count() ] Skipping ReservedInstance ce5ae119-1baf-42a2-b23c-081528c50a58 with state retired
[DEBUG ec2.py:129 - awslimitchecker.services.ec2._get_reserved_instance_count() ] Skipping ReservedInstance bbc4a505-26c3-40a2-80d3-9326de49842b with state retired
[DEBUG ec2.py:129 - awslimitchecker.services.ec2._get_reserved_instance_count() ] Skipping ReservedInstance d02768b8-b517-41fb-acf9-7a449b4a58bc with state retired
[DEBUG ec2.py:129 - awslimitchecker.services.ec2._get_reserved_instance_count() ] Skipping ReservedInstance fa9bc2a4-8a20-43ef-8434-d73e0b3e6e6e with state retired
[DEBUG ec2.py:280 - awslimitchecker.services.ec2._find_usage_networking_sgs() ] Getting usage for EC2 VPC resources
[DEBUG ec2.py:302 - awslimitchecker.services.ec2._find_usage_networking_eips() ] Getting usage for EC2 EIPs
[DEBUG ec2.py:317 - awslimitchecker.services.ec2._find_usage_networking_eni_sg() ] Getting usage for EC2 Network Interfaces
[DEBUG ec2.py:72 - awslimitchecker.services.ec2.find_usage() ] Done checking usage.
[DEBUG vpc.py:61 - awslimitchecker.services.vpc.find_usage() ] Checking usage for service VPC
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region None
[INFO connectable.py:120 - awslimitchecker.connectable.connect() ] Connected to ec2 in region us-east-1
[DEBUG vpc.py:71 - awslimitchecker.services.vpc.find_usage() ] Done checking usage.
[DEBUG ebs.py:61 - awslimitchecker.services.ebs.find_usage() ] Checking usage for service EBS
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region None
[INFO connectable.py:120 - awslimitchecker.connectable.connect() ] Connected to ec2 in region us-east-1
[DEBUG ebs.py:77 - awslimitchecker.services.ebs._find_usage_ebs() ] Getting usage for EBS volumes
[DEBUG ebs.py:125 - awslimitchecker.services.ebs._find_usage_snapshots() ] Getting usage for EBS snapshots
[DEBUG ebs.py:68 - awslimitchecker.services.ebs.find_usage() ] Done checking usage.
[DEBUG elasticache.py:61 - awslimitchecker.services.elasticache.find_usage() ] Checking usage for service ElastiCache
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region None
[INFO connectable.py:120 - awslimitchecker.connectable.connect() ] Connected to elasticache in region us-east-1
[DEBUG elasticache.py:70 - awslimitchecker.services.elasticache.find_usage() ] Done checking usage.
AutoScaling/Auto Scaling groups                        (limit 40) WARNING: 22
EC2/Running On-Demand EC2 instances                    (limit 100) WARNING: 69
EC2/Running On-Demand m3.large instances               (limit 20) CRITICAL: 16
EC2/Running On-Demand t2.micro instances               (limit 20) WARNING: 14
EC2/Running On-Demand t2.small instances               (limit 20) WARNING: 10
EC2/VPC security groups per elastic network interface  (limit 5) CRITICAL: eni-1401b24b=4, eni-1ff46c40=4, eni-ebc45cb4=4 WARNING: eni-7c57e723=3, eni-a5bff882=3, eni-4add6e15=3, eni-4610167a=3, eni-6179825e=3
ELB/Active load balancers                              (limit 40) WARNING: 22
IAM/Server certificates                                (limit 20) WARNING: 12
VPC/Internet gateways                                  (limit 5) CRITICAL: 8
```

### Expected Output

EC2 running instances should have been 74 instead of 69. When using boto3 or the AWS console I get 74.
EC2/Running On-Demand EC2 instances                    (limit 100) WARNING: 74
### Testing Assistance

I will be able to provide testing assistance.

**Comment by jantman** [comment] 2016-07-01 19:51
@yaron-idan sorry, I just noticed this issue now - it looks like the notification got lost in my email.

Before getting too deep into this, do you have any Reserved Instances? They don't count against the On-Demand Running Instances limits, so awslimitchecker subtracts the number of active reserved instances of each type in each AZ from the count of running instances of that type in that AZ. If that's not the issue:

Unfortunately, issues like this are really hard to reproduce. Do you think you could please run the script below and then ``awslimitchecker`` (with ``-vv`` as you did above) in the same virtualenv, one right after another, and then post the output? There shouldn't be any sensitive information in here, and it will at least give me enough to write a unit test for your case and dig into the problem.

```python
#!/usr/bin/env python

import boto3
import time
import json
import calendar

ec2 = boto3.resource('ec2')

data = {'ts': time.time(), 'instances': [], 'reservations': []}

for i in ec2.instances.all():
    info = {}
    for attr in ['id', 'instance_lifecycle', 'instance_type', 'placement',
                 'platform', 'spot_instance_request_id', 'state']:
        info[attr] = getattr(i, attr)
    info['launch_time'] = calendar.timegm(i.launch_time.timetuple())
    data['instances'].append(info)

client = boto3.client('ec2')
for r in client.describe_reserved_instances()['ReservedInstances']:
    info = {}
    for attr in ['State', 'ReservedInstancesId', 'AvailabilityZone',
                 'InstanceType', 'InstanceCount']:
        info[attr] = r[attr]
    data['reservations'].append(info)
print(json.dumps(data))
```

**Comment by yaron-idan** [comment] 2016-07-03 06:12
I do have reserved instances! We have 8 reservations, out of which 6 are utilitzed. That actually explains the gap perfectly. 
Would you still like me to run your code and send you the output or is that enough to close this issue? I would happily help if it gives you any insight about the product, which is really great.

**Comment by jantman** [comment] 2016-07-03 12:28
@yaron-idan Once I looked through the code again, how it handles reservations became really clear - I guess I'd forgotten about that bit.

As long as your reservations match up and account for the discrepancy, I don't see any need for you to run the code. I certainly appreciate the help. awslimitchecker isn't really a "product" - it's a personal project of mine that I can't even work on during the work day :( it's always nice to know it's useful to others.

If it's OK with you, I'm going to close this issue, but open one to clarify this somewhere in the documentation.

**Closed** 2016-07-06 00:51 UTC
