### ISSUE TITLE
Wrong category type in TA check

### ISSUE THREAD

**Issue by quocdung3007** [jantman/awslimitchecker#497] opened 2020-10-16 10:48 UTC
https://github.com/jantman/awslimitchecker/blob/e11bd0aac1c2f6fe23cef173757b5c57318d49fa/awslimitchecker/trustedadvisor.py#L241

When I tried to execute the command: aws support describe-trusted-advisor-checks and I realized that the category name is wrong.

So the correct one should be:
check['category'] == 'service_limits'

Below is the output from the cli:
`{
            "id": "dBkuNCvqn5",
            "name": "RDS Max Auths per Security Group",
            "description": "Checks for usage that is more than 80% of the RDS Max Auths per Security Group Limit. Values are based on a snapshot, so your current usage might differ. Limit and usage data can take up to 24 hours to reflect any changes. In cases where limits have been recently increased, you may temporarily see utilization that exceeds the limit.<br>\n<br>\n<b>Alert Criteria</b><br>\nYellow: 80% of limit reached.<br>\nRed: 100% of limit reached.<br>\nBlue: Trusted Advisor was unable to retrieve utilization or limits in one or more regions.<br>\n<br>\n<b>Recommended Action</b><br>\nIf you anticipate exceeding a service limit, open a case in Support Center to <a href=\"https://aws.amazon.com/support/createCase?type=service_limit_increase\" target=\"_blank\">request a limit increase</a>.<br>\n<br>\n<b>Additional Resources</b><br>\n<a href=\"https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html\" target=\"_blank\">RDS Limits</a>",
            "category": "service_limits",
            "metadata": [
                "Region",
                "Service",
                "Limit Name",
                "Limit Amount",
                "Current Usage",
                "Status"
            ]
        }`

**Comment by jantman** [comment] 2020-12-01 13:50
This is a duplicate of #466 and is also missing the issue template.

**Closed by jantman** 2020-12-01 13:50 UTC
