### ISSUE TITLE
'Max spot instance requests per region' limit check is out of date

### ISSUE THREAD

**Issue by jwu2** [jantman/awslimitchecker#502] opened 2020-11-05 05:03 UTC
### Version

9.0.0

### Installation Method

Docker

### Supporting Software Versions

3.8.6

### Actual Output

Limit of this check always returns 20.

### Expected Output

Refer to <https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html>, this is replaced by following six limits:
  - All F Spot Instance Requests
  - All G Spot Instance Requests
  - All Inf Spot Instance Requests
  - All P Spot Instance Requests
  - All Standard (A, C, D, H, I, M, R, T, Z) Spot Instance Requests
  - All X Spot Instance Requests

### Testing Assistance

Yes

**Comment by nakkurt** [comment] 2020-11-23 17:28
I also ran into this and after speaking with AWS Support I can confirm that the 'Max spot instance requests **per region**' is no longer used by AWS. 
Instead, AWS now manages Spot Instance limits in terms of the number of virtual central processing units (vCPUs) and the above 'per region' request limit is not a thing anymore.

_Implication:_ 
If your code uses `awslimitchecker` to check for '`Max spot instance requests per region`', then you'd probably want to change that until  `awslimitchecker` is updated to better match AWS.

_Background:_
[latest AWS docs on this](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html).

**Comment by jantman** [comment] 2020-12-02 18:11
Apologies for the delay in dealing with this.

So, it looks like the spot instance limits now match up to the on-demand EC2 limits, in that they're vCPU-based. Handling this for EC2 was a pretty big task (for reference, see #432 and https://awslimitchecker.readthedocs.io/en/latest/changes.html#changelog-8-0-0-vcpu-limits ). It's a bit of a pain, because China and GovCloud don't use the vCPU units yet, so two alternate code paths need to be maintained.

I'll do my best to work on this within the next few days or week.

**Comment by jantman** [comment] 2020-12-07 19:44
I've promised a release today that includes a _lot_ of staged changes, and this isn't going to make it. I'm sorry. I'll try to get another out within the next week that includes this.

**Comment by skraga** [comment] 2021-02-18 13:52
We step into the same - adding of this will help us a lot with limits monitoring.

**Comment by jantman** [comment] 2021-08-04 16:10
A fix for this has been released in [12.0.0](https://github.com/jantman/awslimitchecker/releases/tag/12.0.0), which is now live [on PyPI](https://pypi.org/project/awslimitchecker/) and [Docker Hub](https://hub.docker.com/r/jantman/awslimitchecker). Thank you so much!

**Closed by jantman** 2021-08-04 16:10 UTC
Labels: unreleased fix
